# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARICEB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARICEB
  
  pod 'Reusable'
  pod 'FittedSheets'
  pod 'ARCL'

  target 'ARICEBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ARICEBUITests' do
    # Pods for testing
  end

end
